load_module "modules/ngx_rtmp_module.so";

user root;
worker_processes auto;
events { worker_connections 1024; }

rtmp {
    server {
        listen 1935;
        chunk_size 4000;

        application hls_live {
            live on;
            hls on;
            hls_path /run/nginx/stream;
            hls_fragment 3s;              
            hls_playlist_length 60s;
        }
    }
}

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;

        # Cấu hình trả về luồng m3u8 phát trực tiếp
        location /stream {
            add_header 'Access-Control-Allow-Origin' '*' always;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /run/nginx;
        }

        # Sửa lỗi 404 trang chủ: Luôn trả về chữ để UptimeRobot ping thành công
        location / {
            return 200 'Server Stream dang chay ngon lanh 24/7!';
            add_header Content-Type text/plain;
        }
    }
}
